@startuml
'https://plantuml.com/class-diagram

Cinema -- "many" Customer
Cinema -- Controller
class Controller {
    +seating:ArrayList
}

class Cinema {
    -seats: array[][]
    +allocateSeats(seats int):int
    +print()
}
class Customer{
    +id : int
    +seats : String[]
    +print()
    +print(id : int)
}
@enduml